language: "ar_model"

pipeline:
- name: "SpacyNLP"
- name: "lemma_farasa.FarasaLemmatizer"
- name: "SpacyTokenizer"
- name: "RegexFeaturizer"
- name: "SpacyEntityExtractor"
- name: "CRFEntityExtractor"
#  max_iterations: 50
#  L1_c: 0.1
#  L2_c: 0.1
- name: "EntitySynonymMapper"
- name: "SpacyFeaturizer"
# - name: "NGramFeaturizer"
- name: "SklearnIntentClassifier"
#  c: [1, 2, 5, 10, 20, 100]
#  gamma: [0.001]
#  kernels: ['rbf']

policies:
  - name: KerasPolicy
    epochs: 100
    max_history: 5
  - name: FallbackPolicy
    core_threshold: 0.5
    nlu_threshold: 0.3
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy
