pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "RegexFeaturizer"
- name: "SpacyFeaturizer"
- name: "SpacyEntityExtractor"
- name: "CRFEntityExtractor"
- name: "SklearnIntentClassifier"

policies:
  - name: KerasPolicy
    epochs: 100
    max_history: 5
